#!/bin/sh /etc/rc.common

# NIC.br - LAC-BCOP-1 compliance and related functionality
# Copyright (c) 2020 NIC.br
# Distributed under the GPLv2+

START=99
STOP=10
USE_PROCD=1

boot() {
	start "$@"
}

start_service() {
	# Enforce IPv6 blackhole prefix at gateway
	ip route replace blackhole 100::/64 || true
	# LAC-BCOP-1 FR-15: Enable BCP-38 filtering by default on standard configuration
	# IPv6 does loose-mode rpfiltering by default in OpenWRT
	echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
}

#stop_service() {
#	ip route remove blackhole 100::/64 || true
#	echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
#}

reload_service() {
	start "$@"
}

